melos:
  useRootAsPackage: true
  command:
    version:
      fetchTags: false
      message: "chore: release v{new_version} [skip ci]"
      releaseUrl: true
      conventionalCommits:
        types:
          docs:
            bump: patch
            changelog: true
      changelogs:
        - path: CHANGELOG.md
          packageFilters:
            include:
              - hand_drawn_toolkit
    bootstrap:
      usePubspecOverrides: true